### PR TITLE
Build CUDA version as well

### PR DESCRIPTION
**Pull request by mtazzari**
In response to issue https://github.com/mtazzari/galario/issues/156 build CUDA version of GALARIO on top of the CPU version.

### CODE REVIEW

**Comment by fredRos** [comment]
## TLDR
Looking at the failure logs, we can only support py3.7 with a cuda build

## mac
* cudadev seems incompatible with py2.7
* py3.5: binstar connection failed, probably a spurious network issue on the build server
* py3.6: arrays are not contiguous, no idea why that happens only on server. But it built with cuda support

## linux 

* py2.7, py3.5 cudadev doesn't support it

**Comment by mtazzari** [comment]
Thanks for the summary!

First, why did you say that Mac, py3.6 built with cuda support? In the log I read `CUDA_TOOLKIT_ROOT_DIR not found or specified`  (line 436).

I think we can start supporting cuda-enabled builds for python>3.7 on Linux only.
Macs do not have NVIDIA cards anyway, and it's fine to offer new functionality for newer python version. 
Moreover, python 3.7 is not a disruptive release, so it should be easily adoptable.

**Comment by mtazzari** [comment]
> Looking at the failure logs, we can only support py3.7 with a cuda build 

Why do you say that?
In circleCi build py 3.6 in the anaconda environment setup l I read:
```
cudatoolkit-dev:      9.2-py36_2                            conda-forge
```

However, even if it gets installed, later on cmake doesn't find the cuda toolkit..
```
CUDA_TOOLKIT_ROOT_DIR not found or specified
```

**Comment by fredRos** [comment]
> In the log I read CUDA_TOOLKIT_ROOT_DIR not found or specified (line 436).

You are right, missed that. 

> I think we can start supporting cuda-enabled builds for python>3.7 on Linux only.

Yes!

**Comment by jakirkham** [comment]
FWIW we have a method for adding Linux GPU builds to a package if that is of interest.

**Comment by mtazzari** [comment]
Thank you for reporting this! That would be **very** cool for this project. Can you tell us more?

**Comment by jakirkham** [comment]
Sure. Would take a look at the [UCX feedstock]( https://github.com/conda-forge/ucx-split-feedstock ) for an example. The important piece is adding `{{ compiler("cuda") }}` to `requirements/build` and re-rendering.

If you need a CPU only build, then it helps to have a mutex package like `galario-proc` (similar to `ucx-proc` for the UCX case). Also `cuda_compiler_version` will be `None` for the GPU only case and can be used to disable the GPU bits for that build. If you don't need a CPU only build, you can simply add a `skip` for the case when `cuda_compiler_version` is `None`.

Please give this a go in a new PR and we can iterate there.

**Comment by jakirkham** [comment]
Also just a reminder please make sure to fork feedstocks and submit changes from your fork. Thanks! 😄

ref: https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by mtazzari** [comment]
Hey @fredRos if you have time/fancy a go at this...😁

**Comment by jakirkham** [comment]
@mtazzari, when you get a chance, could you please fork this feedstock and resubmit the PR from a branch on your fork? Thanks in advance for working on this 🙂

https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by mtazzari** [comment]
I've forked this repo, I'll open a PR from the fork (and close this PR) as soon as I can, in the next days.

**Comment by mtazzari** [comment]
Getting this done in #8

**Pull request closed without merging**
